<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="3" passed="0" failed="0" skipped="1">
  <reporter-output>
    <line>
      <![CDATA[Suite Execution started - Configure the Reports]]>
    </line>
    <line>
      <![CDATA[createNewOrgTest Test Execution started]]>
    </line>
    <line>
      <![CDATA[createNewOrgTest Test Execution Skipped]]>
    </line>
    <line>
      <![CDATA[Suite Execution ended - Backup the Reports]]>
    </line>
  </reporter-output>
  <suite started-at="2025-07-30T12:35:52 GMT-07:00" name="Default suite" finished-at="2025-07-30T12:35:52 GMT-07:00" duration-ms="141">
    <groups>
      <group name="Smoke">
        <method signature="CreateOrgScenerios.createNewOrgTest()[pri:0, instance:Organization_Module.CreateOrgScenerios@59662a0b]" name="createNewOrgTest" class="Organization_Module.CreateOrgScenerios"/>
      </group> <!-- Smoke -->
    </groups>
    <test started-at="2025-07-30T12:35:52 GMT-07:00" name="Default test" finished-at="2025-07-30T12:35:52 GMT-07:00" duration-ms="141">
      <class name="Organization_Module.CreateOrgScenerios">
        <test-method is-config="true" signature="connectToDatabase()[pri:0, instance:Organization_Module.CreateOrgScenerios@59662a0b]" started-at="2025-07-30T12:35:51 GMT-07:00" name="connectToDatabase" finished-at="2025-07-30T12:35:52 GMT-07:00" duration-ms="1157" status="FAIL">
          <exception class="java.sql.SQLSyntaxErrorException">
            <message>
              <![CDATA[Unknown database 'project']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLSyntaxErrorException: Unknown database 'project'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:815)
at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:438)
at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:189)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
at GenericUtilities.DatabaseUtility.getDatabaseConnection(DatabaseUtility.java:74)
at Base_Class.Base_Class.connectToDatabase(Base_Class.java:41)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLSyntaxErrorException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- connectToDatabase -->
        <test-method is-config="true" signature="conParallel()[pri:0, instance:Organization_Module.CreateOrgScenerios@59662a0b]" started-at="2025-07-30T12:35:52 GMT-07:00" name="conParallel" finished-at="1969-12-31T16:00:00 GMT-08:00" duration-ms="-1753904152612" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- conParallel -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:Organization_Module.CreateOrgScenerios@59662a0b]" started-at="2025-07-30T12:35:52 GMT-07:00" name="launchBrowser" finished-at="1969-12-31T16:00:00 GMT-08:00" duration-ms="-1753904152651" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method is-config="true" signature="login()[pri:0, instance:Organization_Module.CreateOrgScenerios@59662a0b]" started-at="2025-07-30T12:35:52 GMT-07:00" name="login" finished-at="1969-12-31T16:00:00 GMT-08:00" duration-ms="-1753904152684" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="createNewOrgTest()[pri:0, instance:Organization_Module.CreateOrgScenerios@59662a0b]" started-at="2025-07-30T12:35:52 GMT-07:00" name="createNewOrgTest" finished-at="2025-07-30T12:35:52 GMT-07:00" duration-ms="0" status="SKIP">
          <exception class="java.sql.SQLSyntaxErrorException">
            <message>
              <![CDATA[Unknown database 'project']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLSyntaxErrorException: Unknown database 'project'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:815)
at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:438)
at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:189)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
at GenericUtilities.DatabaseUtility.getDatabaseConnection(DatabaseUtility.java:74)
at Base_Class.Base_Class.connectToDatabase(Base_Class.java:41)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLSyntaxErrorException -->
          <reporter-output>
            <line>
              <![CDATA[createNewOrgTest Test Execution Skipped]]>
            </line>
            <line>
              <![CDATA[Suite Execution ended - Backup the Reports]]>
            </line>
          </reporter-output>
        </test-method> <!-- createNewOrgTest -->
        <test-method is-config="true" signature="logOut()[pri:0, instance:Organization_Module.CreateOrgScenerios@59662a0b]" started-at="2025-07-30T12:35:52 GMT-07:00" name="logOut" finished-at="1969-12-31T16:00:00 GMT-08:00" duration-ms="-1753904152709" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOut -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:Organization_Module.CreateOrgScenerios@59662a0b]" started-at="2025-07-30T12:35:52 GMT-07:00" name="closeBrowser" finished-at="1969-12-31T16:00:00 GMT-08:00" duration-ms="-1753904152720" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="closeConParallel()[pri:0, instance:Organization_Module.CreateOrgScenerios@59662a0b]" started-at="2025-07-30T12:35:52 GMT-07:00" name="closeConParallel" finished-at="1969-12-31T16:00:00 GMT-08:00" duration-ms="-1753904152727" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeConParallel -->
        <test-method is-config="true" signature="closeDatabaseConnection()[pri:0, instance:Organization_Module.CreateOrgScenerios@59662a0b]" started-at="2025-07-30T12:35:52 GMT-07:00" name="closeDatabaseConnection" finished-at="1969-12-31T16:00:00 GMT-08:00" duration-ms="-1753904152918" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDatabaseConnection -->
      </class> <!-- Organization_Module.CreateOrgScenerios -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
